# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SparkFun Inventor's Kit
title_seperator: "-"
subtitle: "Online and Interactive MicroPython Exploration"
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Home of the SparkFun Inventor's Kit - MicroPython
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sparkfun.fun" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  gigapod
breadcrumbs: true  # disabled by default


# Build settings
# theme: minima
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin    : "default"
# minimal_mistakes_skin: "default"

logo: "/assets/images/sfe-flame-88.png"



plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-target-blank

markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
permalink: pretty

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

search: true
search_full_content: true
search_provider: lunr
# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/sparkfun"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sparkfun"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/sparkfun"
    - label: "youtube"
      icon: "fab fa-fw fa-youtube-square"
      url: "https://www.youtube.com/user/sparkfun"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      share: false
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc_sticky: true
      sidebar:
        nav: "docs"

# Reading Files
include: 
  - _pages
  - _posts
  - _includes
  - _layouts
  - _assets
  - _docs
  - assets/images
  
encoding: "utf-8"

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp